### ISSUE TITLE
Unused option "rejoin"

### ISSUE THREAD

**Issue by allonhadaya** [nickvanw/ircx#8]
Hi, I noticed that bot currently defines a default option with the key "rejoin" [here](https://github.com/nickvanw/ircx/blob/8706e82ad443e904aee12c41eb1d44da900a3817/bot.go#L31). It doesn't seem to be used anywhere. Is it a leftover from old functionality, or something else I'm not seeing?

**Comment by nickvanw** [comment]
Hi @allonhadaya!

I wrote `ircx` a while ago as a framework for a more fully fledged IRC bot, [bogon](https://github.com/nickvanw/bogon)

It looks like I left those defaults in so that I could use them [here](https://github.com/nickvanw/bogon/blob/master/state/kick.go#L16), as configuration to rejoin a channel when the bot has been kicked. I don't believe they're used inside this project, I'll go ahead and open a PR to remove the key!

**Comment by allonhadaya** [comment]
Cool, I'll check out bogon. Thanks!

**Comment by nickvanw** [comment]
PR has been merged that removes this, once #15 is in, there will be no more magic "config" values!
